version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "Postgres2019!"
    ports:
      - "15432:5432"
    volumes:
      - /home/iamthemage/Develop/PostgreSQL:/var/lib/postgresql/data 
    networks:
      - postgres-compose-network
      
  pg_admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "gustavosjn2013@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2019!"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - postgres-compose-network

  redis:
    container_name: redis-container
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data

networks: 
  postgres-compose-network:
    driver: bridge